'\" t
.\"     Title: heap2exec
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-11-04
.\"    Manual: \ \&
.\"    Source: SML/NJ
.\"  Language: English
.\"
.TH "HEAP2EXEC" "1" "2025-11-04" "SML/NJ" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
heap2exec \- generate standalone executable from a *SML/NJ* heap image.
.SH "SYNOPSIS"
.sp
\fBheap2exec\fP [ \fB\-32\fP | \fB\-64\fP ] [ \fILINKMODE\fP ] \fIfile\fP
.SH "DESCRIPTION"
.sp
Under normal usage, \fBSML/NJ\fP represents a program as a heap\-image file
with a name of the form \f(CRfoo.arch\-opsys\fP
\fBHeap2exec\fP generates a standalone executable from a heap image.
You have the option to specify a preferred linking mode.
.sp
The default is to link statically on \fBFreeBSD\fP and \fBLinux\fP.
.sp
Note that \fBheap2exec\fP is an \fIoptional\fP component of the SML/NJ
installation process that is not included by default.  Edit the
\f(CRconfig/targets\fP file before installation to include it.
.SH "OPTIONS"
.sp
\fB\-32\fP
.RS 4
run the 32\-bit version of the program (currently the default).
.RE
.sp
\fB\-64\fP
.RS 4
run the 64\-bit version of the program.  This option only applies to
the \fBx86\-64\fP (aka \fBamd64\fP) architecture.
.RE
.sp
\fB\-static, \-linkwith\-a\fP
.RS 4
statically link the program with the runtime system.  Static linking
is the default on \fBLinux\fP and \fBFreeBSD\fP.
.RE
.sp
\fB\-dynamic, \-linkwith\-so\fP
.RS 4
dynamically link the program with the runtime system.
.RE
.SH "AUTHOR"
.sp
\fBHeap2exec\fP was written by Matthias Blume.
.SH "SEE\-ALSO"
.sp
sml(1)
.SH "BUGS"
.sp
\fBHeap2exec\fP is limited to the \fBx86\fP and \fBamd64\fP architectures and to the
\fBmacOS\fP, \fBLinux\fP, and \fBFreeBSD\fP operating systems.
.SH "COPYING"
.sp
Copyright \(co 2020 The Fellowship of SML/NJ
.sp
This is free software; see the source for copying  conditions.   There  is  NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.