'\" t
.\"     Title: ml-makedepend
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-11-04
.\"    Manual: \ \&
.\"    Source: SML/NJ
.\"  Language: English
.\"
.TH "ML\-MAKEDEPEND" "1" "2025-11-04" "SML/NJ" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
ml-makedepend \- makefile dependency generator for SML/NJ programs
.SH "SYNOPSIS"
.sp
\fBml\-makedepend\fP [\fIOPTIONS\fP] \fIproject.cm\fP \fItarget\fP
.SH "DESCRIPTION"
.sp
\fBML\-Makedepend\fP is a tool for generating dependency information to allow the
Unix \fBmake\fP(1) program to be used to build SML/NJ programs.
.SH "OPTIONS"
.sp
\fB\-f\fP \fImakefile\fP
.RS 4
Specify the name of the makefile to which the dependency information is appended.  If this
option is \fInot\fP given, then the output is appended to the end of the file \f(CRmakefile\fP
(or \f(CRMakefile\fP).  It is an error if neither file exists and the \fB\-f\fP option is not specified.
.RE
.sp
\fB\-a\fP \fIarch\fP
.RS 4
specifies the name a make variable for architecture\-specific filenames and paths
(the default is \f(CRARCH\fP).
.RE
.sp
\fB\-o\fP \fIos\fP
.RS 4
specifies the name a make variable for operating\-system\-specific filenames and paths
(the default is \f(CROPSYS\fP).
.RE
.sp
\fB\-n\fP
.RS 4
generates full filenames and paths with any architecture or operating\-system\-specific
parts expanded out to their definition for the host system.  If this option is specified,
then any \fB\-a\fP and \fB\-o\fP options are ignored.
.RE
.sp
\fB\-C\fP\fIctl\fP=\fIvalue\fP
.RS 4
set the control \fIctl\fP to \fIvalue\fP.
.RE
.sp
\fB\-D\fP\fIname\fP=\fIvalue\fP
.RS 4
define the CM variable \fIname\fP to have the given value.
.RE
.sp
\fB\-D\fP\*(Aqname
.RS 4
define the CM variable \fIname\fP to have the value 1.
.RE
.sp
\fB\-U\fP\fIname\fP
.RS 4
remove any definition of the CM variable \fIname\fP.
.RE
.SH "AUTHOR"
.sp
\fBML\-Makedepend\fP was written by Matthias Blume.
.SH "SEE\-ALSO"
.sp
\fBml\-build\fP(1), \fBsml\fP(1), \fBsmlnj\fP(7)
.SH "COPYING"
.sp
Copyright \(co 2020 The Fellowship of SML/NJ
.sp
This is free software; see the source for copying  conditions.   There  is  NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.